import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import HomeForm from './components/homeForm'

export default function Home() {
  return (
    <div className={styles.container}>
      
      <Head>
        <title>Galerapagos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>

      <main className={styles.main}>
        <Image src="/logo-galerapagos.png" alt="Logo" width={1000} height={322} />
        <div>
          <HomeForm/>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span className={styles.logo}>
            <Image src="/logo.ico" alt="Logo" width={100} height={20} />
          </span>
        </a>
      </footer>
    </div>
  )
}
