import React from "react";
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import HomeForm from './components/homeForm'
import PlayersForm from './components/playersForm'
import GameForm from './components/gameForm'

const HOME_FORM = 0;
const PLAYERS_FORM = 1;
const GAME_FORM = 2;

class Home extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      stepForm : HOME_FORM,
      nbPlayers : 0,
      nbTurns : 0,
      players : [],
    };
    this.handleSubmitHomeForm = this.handleSubmitHomeForm.bind(this);
    this.handleSubmitPlayersForm = this.handleSubmitPlayersForm.bind(this);
  }

  handleSubmitHomeForm(nbPlayers,nbTurns){
    this.setState({"nbPlayers" : nbPlayers, "nbTurns" : nbTurns, stepForm : PLAYERS_FORM})
  }

  handleSubmitPlayersForm(players){
    this.setState({"players" : players, stepForm : GAME_FORM})
  }

  render() {
    return (
      <div className={styles.container}>
      <Head>
        <title>Galerapagos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      {
        this.state.stepForm == HOME_FORM && (
          <main className={styles.main}>
          <Image src="/logo-galerapagos.png" alt="Logo" width={1000} height={322} />
          <div>
            <HomeForm onSubmit={this.handleSubmitHomeForm}/>
          </div>
        </main>
        )
      }
      {
        this.state.stepForm == PLAYERS_FORM && (
          <PlayersForm nbPlayers={this.state.nbPlayers} onSubmit={this.handleSubmitPlayersForm}/>
        )
      }
      {
        this.state.stepForm == GAME_FORM && (
          <GameForm players={this.state.players}/>
        )
      }




      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span className={styles.logo}>
            <Image src="/logo.ico" alt="Logo" width={100} height={20} />
          </span>
        </a>
      </footer>
    </div>
    );
  }
}

export default Home;
